# -*- coding: utf-8 -*-
"""Практическая 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LhcsJQC9MZ7YI73gIp1E1oKYkYwNNYBn
"""

class Person:
    def __init__(self, name, surname, qualification = 1):
      self.name = name
      self.surname = surname
      self.qualification = qualification
     
    def display(self):
        return self.name, self.surname, self.qualification

    def __del__(self):
        print('До свидания, мисс {} {}'.format(self.name, self.surname))

p1 = Person('Марина', 'Шишкина', 3)
print(p1.display())

p2 = Person('Настя', 'Сладких', 2)
print(p2.display())

p3 = Person('Люда', 'Королёва', 1)
print(p3.display())
del p2

try:
    input('Press Enter and exit')
except SyntaxError:
    exit()

class Student:
    def __init__(self ,surname ,university, gender, progress, group="АДЭУ-211"):
        self.surname = surname
        self.university = university
        self.gender = gender
        self.progress = progress
        self.group = group

    def __del__(self):
        print('Отчислен студент -',self.surname,self.progress)

    def info(self):
        return "{0} - {1},{2},{3},{4}".format(self.surname, self.university, self.gender, self.progress, self.group)


st1=Student('Васильева',' MГПУ', ' Женский ', 'отличник ')
st2=Student('Романов',' MГПУ', ' Мужской ', 'ударник ')
student_3=Student('Андриянова',' MГПУ', ' Женский ', 'задолжник ' )  
print(st1.info())
print(st2.info())
print(student_3.info())